### ISSUE TITLE
Errors in server console

### ISSUE THREAD

**Issue by Enritix** [Luke100000/ImmersivePaintings#29]
The server keeps lagging because these errors keep coming up about a lot of different files that it's saying it can't find.
I've tried to look for the cache folder but I can't find it nowhere.
Is there any way to fix this?

```
[07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: java.io.FileNotFoundException: ./immersive_paintings_cache/d7721fe2-a713-476c-8a62-679fbb82c2c7_thumbnail.png (No such file or directory)
10971 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at java.base/java.io.FileOutputStream.open0(Native Method)
10972 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at java.base/java.io.FileOutputStream.open(Unknown Source)
10973 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
10974 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
10975 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/immersive_paintings@0.4.4+1.19.2/immersive_paintings.resources.Cache.set(Cache.java:51)
10976 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/immersive_paintings@0.4.4+1.19.2/immersive_paintings.resources.ServerPaintingManager.getImageData(ServerPaintingManager.java:144)
10977 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/immersive_paintings@0.4.4+1.19.2/immersive_paintings.network.c2s.ImageRequest.receive(ImageRequest.java:31)
10978 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/immersive_paintings@0.4.4+1.19.2/immersive_paintings.forge.cobalt.network.NetworkHandlerImpl.lambda$registerMessage$2(NetworkHandlerImpl.java:31)
10979 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68)
10980 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
10981 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
10982 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
10983 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
10984 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:763)
10985 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:157)
10986 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
10987 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:746)
10988 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:740)
10989 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
10990 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:725)
10991 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2131)
10992 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
10993 | [07Feb2023 22:00:29.890] [Server thread/ERROR] [STDERR/]: 	at java.base/java.lang.Thread.run(Unknown Source)
10994 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: java.io.FileNotFoundException: ./immersive_paintings_cache/907462cd-02a8-4934-a99d-ff977b4ee666_thumbnail.png (No such file or directory)
10995 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at java.base/java.io.FileOutputStream.open0(Native Method)
10996 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at java.base/java.io.FileOutputStream.open(Unknown Source)
10997 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
10998 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
10999 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/immersive_paintings@0.4.4+1.19.2/immersive_paintings.resources.Cache.set(Cache.java:51)
11000 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/immersive_paintings@0.4.4+1.19.2/immersive_paintings.resources.ServerPaintingManager.getImageData(ServerPaintingManager.java:144)
11001 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/immersive_paintings@0.4.4+1.19.2/immersive_paintings.network.c2s.ImageRequest.receive(ImageRequest.java:31)
11002 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/immersive_paintings@0.4.4+1.19.2/immersive_paintings.forge.cobalt.network.NetworkHandlerImpl.lambda$registerMessage$2(NetworkHandlerImpl.java:31)
11003 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68)
11004 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
11005 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
11006 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
11007 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
11008 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:763)
11009 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:157)
11010 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
11011 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:746)
11012 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:740)
11013 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
11014 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:725)
11015 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2131)
11016 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
11017 | [07Feb2023 22:00:29.898] [Server thread/ERROR] [STDERR/]: 	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by DownloadableFox** [comment]
I'm also having this bug.

**Comment by sedyh** [comment]
Same for me, how can I get the updated version (> 0.4.4)?

**Comment by Luke100000** [comment]
Curseforge or modrinth since 10 minutes

**Comment by VaelophisNyx** [comment]
getting this same error on 0.5.0

**Comment by Luke100000** [comment]
Can you please share the log too to make sure its indeed the same?

**Comment by VaelophisNyx** [comment]
```
[Server] Server thread/[INFO] [STDERR]: java.io.FileNotFoundException: ./immersive_paintings_cache/968961ea-5a43-48a5-80d4-dd1a5ce90b40_half.png (No such file or directory)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at java.base/java.io.FileOutputStream.open0(Native Method)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at immersive_paintings.resources.Cache.set(Cache.java:52)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at immersive_paintings.resources.ServerPaintingManager.getImageData(ServerPaintingManager.java:142)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at immersive_paintings.network.c2s.ImageRequest.receive(ImageRequest.java:31)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at immersive_paintings.fabric.cobalt.network.NetworkHandlerImpl.lambda$registerMessage$0(NetworkHandlerImpl.java:40)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.class_3738.run(class_3738.java:18)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.class_1255.method_18859(class_1255.java:157)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.class_4093.method_18859(class_4093.java:23)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.class_1255.method_16075(class_1255.java:131)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
16.03 16:08:10 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.class_1255.method_18857(class_1255.java:140)
16.03 16:08:14 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
16.03 16:08:14 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.server.MinecraftServer.handler$bma000$carpet$modifiedRunLoop(MinecraftServer.java:6894)
16.03 16:08:14 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
16.03 16:08:14 [Server] Server thread/[INFO] [STDERR]: at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
16.03 16:08:14 [Server] Server thread/[INFO] [STDERR]: at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Luke100000** [comment]
Thanks! Found a typo most likely causing this issue.

**Comment by Luke100000** [comment]
Ok next attempt, 0.5.1 should now fix it, should be available within 20 minutes

**Comment by VaelophisNyx** [comment]
sick!
