### ISSUE TITLE
Same painting

### ISSUE THREAD

**Issue by OctoDrakelevrai** [Luke100000/ImmersivePaintings#35]
I use the mod to troll my friends but the painting are bug. I importe 1 painting and I place it but when I want a different painting the first come back

<img width="896" alt="qdsf" src="https://user-images.githubusercontent.com/130861743/232246058-437d3ec6-ba5e-4f7a-8578-d17dbcbdacdd.PNG">

![2023-04-15_19 59 19](https://user-images.githubusercontent.com/130861743/232246062-4e988259-4f30-4ca5-8116-d6cb6c4693ae.png)

![2023-04-15_19 59 40](https://user-images.githubusercontent.com/130861743/232246065-377c36e8-bf74-4480-8408-0c303f62c51b.png)

![2023-04-15_19 59 52](https://user-images.githubusercontent.com/130861743/232246070-f65f9543-f134-4269-aded-00a0e76e7a92.png)

Before
![2023-04-15_20 07 14](https://user-images.githubusercontent.com/130861743/232246155-3f2e0050-7128-4ffd-ba21-8c5ebda6d63b.png)
After
![2023-04-15_20 08 16](https://user-images.githubusercontent.com/130861743/232246161-b99836a0-8c24-41e3-b54a-d91717d9d1a7.png)

I have delete the picture on my pc but the bug persists

It the same probleme for the grafiti
Thanks for helping me 🟦⬜🟥🥐🥖

**Comment by OctoDrakelevrai** [comment]
I play in 1.19.4 with Fabric 0.14.18 and these mods :
<img width="319" alt="dsgf" src="https://user-images.githubusercontent.com/130861743/232246697-91705221-72f1-4375-a053-6d18a8b21b18.PNG">

**Comment by Luke100000** [comment]
Note the name. If you choose the same name it overwrites the existing one.

**Comment by voidpointer0x00** [comment]
Same, can't figure out the reason, seems like something related to the way client sends a painting to the server
```
java.lang.RuntimeException: javax.imageio.IIOException: Error reading PNG image data
        at immersive_paintings.network.SegmentedPaintingMessage.receive(SegmentedPaintingMessage.java:55) ~[immersive_paintings-git-c87820f.jar:?]
        at immersive_paintings.fabric.cobalt.network.NetworkHandlerImpl.lambda$registerMessage$1(NetworkHandlerImpl.java:36) ~[immersive_paintings-git-
c87820f.jar:?]
...
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:244) ~[?:?]
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:?]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:244) ~[?:?]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
        at java.io.DataInputStream.readFully(DataInputStream.java:201) ~[?:?]
        at com.sun.imageio.plugins.png.PNGImageReader.decodePass(PNGImageReader.java:1245) ~[?:?]
        at com.sun.imageio.plugins.png.PNGImageReader.decodeImage(PNGImageReader.java:1381) ~[?:?]
        at com.sun.imageio.plugins.png.PNGImageReader.readImage(PNGImageReader.java:1521) ~[?:?]
        at com.sun.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:1847) ~[?:?]
        at javax.imageio.ImageIO.read(ImageIO.java:1470) ~[?:?]
        at javax.imageio.ImageIO.read(ImageIO.java:1365) ~[?:?]
        at immersive_paintings.resources.ByteImage.read(ByteImage.java:28) ~[immersive_paintings-git-c87820f.jar:?]
        at immersive_paintings.resources.ByteImage.read(ByteImage.java:52) ~[immersive_paintings-git-c87820f.jar:?]
        at immersive_paintings.network.SegmentedPaintingMessage.receive(SegmentedPaintingMessage.java:52) ~[immersive_paintings-git-c87820f.jar:?]
        ... 12 more
```

**Comment by Crowlog** [comment]
I have the same problem and a new instance of mc also doesnt fix the issue. It works fine in singleplayer but when i join my friends server i cant change the picture that is uploaded anymore.

**Comment by OuToU1** [comment]
To fix this, go to **immersive_paintings\immersive_paintings_USERWITHISSUE**, remove the picture that keeps appearing and restart the server.
